server:
  port: 7777
  
logging:
  level:
    com.jatis.demo: debug
    org.springframework.security: debug

spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
  datasource:
    username: demo-api
    password: password
    url: jdbc:h2:~/demo-api
    hikari:
      maximum-pool-size: 10

jwt.signature.cert.der: /home/hwicaksono/wso2.crt
#jwt.signature.cert.der: n/a
jwt.token.header: X-Auth-Token